<?php

use Illuminate\Support\Facades\Route;

Route::get('dashboard', App\Livewire\Eventner\Dashboard::class)->name('eventner.dashboard');
Route::get('format-nilai', App\Livewire\Eventner\FormatNilai\Builder::class)->name('eventner.format-nilai.builder');
Route::get('format-nilai/pdf', [App\Http\Controllers\Eventner\FormatNilaiController::class, 'downloadPdf'])->name('eventner.format-nilai.pdf');
Route::get('judges', App\Livewire\Eventner\Judge\Index::class)->name('eventner.judges.index');
Route::get('competition-categories', App\Livewire\Eventner\CompetitionCategory\Index::class)->name('eventner.competition-categories.index');
Route::get('participants', App\Livewire\Eventner\Participant\Index::class)->name('eventner.participants.index');
Route::get('participants/{registration}/pdf', [App\Http\Controllers\Eventner\ParticipantController::class, 'downloadPdf'])->name('eventner.participants.pdf');
Route::get('vote-settings', App\Livewire\Eventner\VoteSettings\Index::class)->name('eventner.vote-settings.index');
Route::get('vote-booster', App\Livewire\Eventner\VoteBooster\Index::class)->name('eventner.vote-booster.index');
Route::get('vote-results', App\Livewire\Eventner\VoteResults\Index::class)->name('eventner.vote-results.index');
Route::get('vote-results/pdf', [App\Http\Controllers\Eventner\VoteResultsController::class, 'downloadPdf'])->name('eventner.vote-results.pdf');
Route::get('vote-results/{registration}', App\Livewire\Eventner\VoteResults\Show::class)->name('eventner.vote-results.show');
Route::get('vote-transactions', App\Livewire\Eventner\VoteTransaction\Index::class)->name('eventner.vote-transactions.index');
Route::get('vote-transactions/csv', [App\Http\Controllers\Eventner\VoteTransactionController::class, 'downloadCsv'])->name('eventner.vote-transactions.csv');
Route::get('profile', App\Livewire\Eventner\Settings\Profile::class)->name('eventner.profile.index');
Route::get('bank-accounts', App\Livewire\Eventner\Settings\BankAccount::class)->name('eventner.bank-accounts.index');
Route::get('score-recap', App\Livewire\Eventner\ScoreRecap\Index::class)->name('eventner.score-recap.index');
Route::get('scoring/csv', [App\Http\Controllers\Eventner\ScoringController::class, 'downloadCsv'])->name('eventner.scoring.csv');
Route::get('scoring/pdf-participant', [App\Http\Controllers\Eventner\ScoringController::class, 'downloadParticipantPdf'])->name('eventner.scoring.pdf-participant');
Route::get('scoring', App\Livewire\Eventner\Scoring\Index::class)->name('eventner.scoring.index');
Route::get('champion-categories', App\Livewire\Eventner\ChampionCategory\Index::class)->name('eventner.champion-categories.index');
Route::get('champion-categories/pdf', [App\Http\Controllers\Eventner\ChampionCategoryController::class, 'downloadPdf'])->name('eventner.champion-categories.pdf');
Route::get('tickets', App\Livewire\Eventner\Ticket\Index::class)->name('eventner.tickets.index');
Route::get('tickets/settings', App\Livewire\Eventner\Ticket\Settings::class)->name('eventner.tickets.settings');
Route::get('activity-log', App\Livewire\Eventner\ActivityLog\Index::class)->name('eventner.activity-log.index');
Route::get('drawing', App\Livewire\Eventner\Drawing\Index::class)->name('eventner.drawing.index');
Route::get('drawing/print', [App\Http\Controllers\Eventner\DrawingController::class, 'print'])->name('eventner.drawing.print');
Route::get('livestream', App\Livewire\Eventner\Livestream\Manage::class)->name('eventner.livestream.index');
Route::get('faq', App\Livewire\Eventner\Faq\Index::class)->name('eventner.faq.index');
Route::get('gallery', App\Livewire\Eventner\Gallery\Index::class)->name('eventner.gallery.index');
Route::get('sponsors', App\Livewire\Eventner\Sponsor\Index::class)->name('eventner.sponsors.index');
Route::get('tenants', App\Livewire\Eventner\Tenant\Index::class)->name('eventner.tenants.index');
Route::get('finance', App\Livewire\Eventner\FinanceDashboard::class)->name('eventner.finance.index');
Route::get('event-qr', App\Livewire\Eventner\EventQr::class)->name('eventner.event-qr.index');
Route::get('certificate', App\Livewire\Eventner\Certificate\Templates::class)->name('eventner.certificate.index');
Route::get('certificate/{template}/editor', App\Livewire\Eventner\Certificate\Editor::class)->name('eventner.certificate.editor');
Route::get('certificate/pdf', [App\Http\Controllers\Eventner\CertificateController::class, 'downloadPdf'])->name('eventner.certificate.pdf');
